stages:
  - publish
  - test
  - deploy

cache:
  paths:
    - .m2/repository
    - target/

publish_stag:
  image: mwienk/docker-lftp
  stage: publish
  script:
    - echo "Simply copy the files to staging server"
    - lftp -u $JS_STAGE_FTP_U,$JS_STAGE_FTP_PWD $JS_ADD -e "set ftp:ssl-allow no ; mirror -e -R -x .gitlab-ci.yml -x .git -x languages/ -x blog/ -x test/ -p ./ / ; quit"
    - echo "Copy complete"
  environment:
    name: staging
    url: http://staging.jonathansolis.com
  only:
  - master

generic_test:
  variables:
    # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
    # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
    MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
    # when running from the command line.
    # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  image: markhobson/maven-chrome:jdk-11
  stage: test
  script: 
    - echo "Running UI staging tests with selenium in java"
    - cd test/Java-Selenium
    - mvn compile
    - mvn test -Dtest=com.jonathan.JonathanTests
  artifacts:
    when: always
    reports:
      junit:
        - test/Java-Selenium/target/surefire-reports/TEST-*.xml

deploy_prod:
  image: mwienk/docker-lftp
  stage: deploy
  script:
    - echo "Deploy to production server"
    - lftp -u $JS_PROD_FTP_U,$JS_PROD_FTP_PWD $JS_ADD -e "set ftp:ssl-allow no ; mirror -e -R -x .gitlab-ci.yml -x .git -x languages/ -x blog/ -x test/ -p ./ / ; quit"
    - echo "Deployment to production complete"
  environment:
    name: production
    url: http://jonathansolis.com
  only:
  - master
