stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"

build:
  stage: build
  script: echo "Building the app"s

deploy_staging:
  image: mwienk/docker-lftp
  stage: deploy
  script:
    - echo "Deploy to staging server"
    - lftp -u $JS_STAGE_FTP_U,$JS_STAGE_FTP_PWD $JS_ADD -e "set ftp:ssl-allow no ; mirror -e -R -x .gitlab-ci.yml -x .git -x languages/ -x blog/ -p ./ / ; quit"
    - echo "Deployment complete"
  environment:
    name: staging
    url: http://staging.jonathansolis.com
  only:
  - master

deploy_prod:
  image: mwienk/docker-lftp
  stage: deploy
  script:
    - echo "Deploy to production server"
    - lftp -u $JS_PROD_FTP_U,$JS_PROD_FTP_PWD $JS_ADD -e "set ftp:ssl-allow no ; mirror -e -R -x .gitlab-ci.yml -x .git -x languages/ -x blog/ -p ./ / ; quit"
    - echo "Deployment to production complete"
  environment:
    name: production
    url: http://jonathansolis.com
  when: manual
  only:
  - master